#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.

#ENGINE_ROOT = File.expand_path('../..', __FILE__)
#ENGINE_PATH = File.expand_path('../../lib/full_and_mountable/engine', __FILE__)

#require 'rails/all'
#require 'rails/engine/commands'



APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require 'rails/commands'

require 'rails/all'

